name: "publish"

on:
  workflow_dispatch:

env:
  RELEASE_TITLE: "build ${{github.run_number}}"
  RELEASE_TAG: "v${{github.run_number}}"
  RELEASE_FILE: "build/libs/*-v${{github.run_number}}.jar"

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        branch: [ '1.16.1' ]
    steps:
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ matrix.branch }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build artifacts - ${{ matrix.branch }}
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: ${{ env.RELEASE_FILE }}
  publish:
    runs-on: "ubuntu-latest"
    needs: build
    if: always() && (needs.build.result == 'success')
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: download
        with:
          path: build/results
      - name: Publish tagged version
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{ env.RELEASE_TAG }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{ env.RELEASE_TITLE }}
          files: |
            LICENSE*
            ${{ env.RELEASE_FILE }}
      - name: Publish latest
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{ env.RELEASE_TITLE }}
          files: ${{steps.download.outputs.download-path}}