name: "test"

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build artifacts
        run: ./gradlew build